# Generated by Django 3.2.4 on 2023-02-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0007_alter_order_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cd', 'Cash On Delivery'), ('cc', 'Credit Card'), ('dc', 'Debit Card'), ('pp', 'PayPal'), ('st', 'Stripe'), ('ap', 'Apple Pay'), ('gp', 'Google Pay'), ('up', 'UPI')], max_length=2),
        ),
    ]
