# Generated by Django 3.2.4 on 2023-02-24 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0009_order_order_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, upload_to='logo/')),
                ('logo_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='PaymentPartners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True)),
                ('partner', models.ImageField(blank=True, null=True, upload_to='payment_partners/')),
            ],
        ),
        migrations.CreateModel(
            name='WidgetNewsLetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=10)),
                ('text', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=10)),
                ('links', models.ManyToManyField(to='ecommerce_app.Link')),
            ],
        ),
        migrations.CreateModel(
            name='Navbar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('links', models.ManyToManyField(to='ecommerce_app.Link')),
                ('logo', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='nav_bar', to='ecommerce_app.logo')),
            ],
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moto', models.CharField(max_length=255)),
                ('logo', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='footer', to='ecommerce_app.logo')),
                ('news_letter', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='footer', to='ecommerce_app.widgetnewsletter')),
                ('payment_partners', models.ManyToManyField(related_name='footer', to='ecommerce_app.PaymentPartners')),
                ('widgets', models.ManyToManyField(related_name='footer', to='ecommerce_app.Widget')),
            ],
        ),
    ]
