# Generated by Django 3.2.4 on 2023-02-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0011_alter_widgetnewsletter_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widgetnewsletter',
            name='text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
