# Generated by Django 3.2.4 on 2023-03-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0012_alter_widgetnewsletter_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='footer_text',
            field=models.CharField(default='Copyright © 20232020 All rights reserved | This template is made with <3 by Colorlib', max_length=255),
        ),
    ]
