# Generated by Django 3.2.4 on 2023-03-07 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0013_footer_footer_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shortdes',
            field=models.CharField(max_length=191),
        ),
    ]
