# Generated by Django 3.2.4 on 2023-03-08 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0014_alter_product_shortdes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='footer_text',
            field=models.TextField(default='Copyright © 20232020 All rights reserved | This template is made with <3 by Colorlib', max_length=255),
        ),
    ]
