# Generated by Django 3.2.4 on 2023-03-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0020_auto_20230309_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='expiration',
            field=models.DateField(),
        ),
    ]
