# Generated by Django 3.2.4 on 2023-03-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0021_alter_offer_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='expiration',
            field=models.DateTimeField(),
        ),
    ]
