# Generated by Django 3.2.4 on 2023-03-10 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0022_alter_offer_expiration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('map', models.CharField(max_length=1000)),
                ('text', models.TextField()),
            ],
        ),
    ]
