# Generated by Django 3.2.4 on 2023-03-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0023_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='map',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
