# Generated by Django 3.2.4 on 2023-03-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0025_pagesection'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('sections', models.ManyToManyField(related_name='About', to='ecommerce_app.PageSection')),
            ],
        ),
    ]
