# Generated by Django 3.2.4 on 2023-03-31 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0028_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=191)),
                ('postedBy', models.CharField(max_length=191)),
                ('postedOn', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, upload_to='blog_images/')),
                ('text', models.TextField()),
            ],
        ),
    ]
